channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.0
- pip:
  - mlflow==2.14.3
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost==3.0.0
name: mlflow-env
