channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.0
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.3
  - psutil==6.1.0
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
